---
description: 'Дополнительные сведения о: "Catch" не может использоваться после "finally" в операторе "try"'
title: В операторе Try слово Catch не может следовать после Finally
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ec177fadf2490c3779e0ad3a1f754319e12bd9cc
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100454954"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>В операторе Try слово Catch не может следовать после Finally

Оператор `Catch` встречается в коде после оператора `Finally` , завершающего блок операторов `Try` . `Catch` должен находиться внутри блока операторов `Try...Catch...Finally` .  
  
 **Идентификатор ошибки:** BC30379  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
1. Переместите оператор `Catch` в более подходящее место в коде.  
  
## <a name="see-also"></a>См. также раздел

- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
