---
description: 'Дополнительные сведения: "Catch" не может находиться за пределами оператора "try"'
title: Catch не может использоваться вне тела оператора Try
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 4ac18a51602c7dc5c4d7b397e1b64f9ed77fcc87
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473905"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>Catch не может использоваться вне тела оператора Try

`Catch` должен находиться внутри блока операторов `Try...Catch...Finally` . В блоке `Catch` есть ненужный оператор `Try` , или оператор `Catch` находится за пределами соответствующего блока `Try` .  
  
 **Идентификатор ошибки:** BC30380  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
1. Удалите оператор `Catch` , если он не нужен, или поместите его в блок операторов `Try...Catch...Finally` .  
  
## <a name="see-also"></a>См. также раздел

- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
